name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: europe-west3-docker.pkg.dev/cnpe-blue/sockshop 
      COMMIT: ${{ github.sha }}
      REPO: queue-master
    steps:
    - uses: actions/checkout@v2


    - uses: actions/setup-java@v1
      with:
        java-version: '8' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

 
    #
    #
    # Build
    - name: Build jar files
      run: ./scripts/build.sh

    #
    #
    # Unit test
    - name: Run unit tests
      run: ./test/test.sh unit.py

    #
    #
    # Component test
    - name: Run component tests
      run: ./test/test.sh component.py
      
    #
    #
    # Push to dockerhub
    - name: Build image
      uses: docker/build-push-action@v1
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        push: false
        repository: ${{ env.GROUP }}/${{ env.REPO }}
        tag_with_ref: true
        tag_with_sha: true
        path: docker/queue-master
        dockerfile: docker/queue-master/Dockerfile
        
     # Push to GAR
    - name: Login to GAR
      uses: docker/login-action@v1
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        registry: europe-west3-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GAR_JSON_KEY }}

    - name: Push to GAR
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      run: docker push ${{ env.GROUP }}/${{ env.REPO }} --all-tags  
